import Head from "next/head";
import Admin from "../components/Admin";
import Login from "../components/Login";
import Student from "../components/Student";
import Teacher from "../components/Teacher";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Admin />
      </main>
    </div>
  );
}
